### ISSUE TITLE
Conditions based on groups

### ISSUE THREAD

**Issue by GuillaumeSorel** [StaxWP/visibility-logic-elementor#2]
This option would be great in order to mix roles and groups. For example, I have a role 'user' and the user can belong to 2 different groups 'active' & 'passive' and it would be great to grant or not access to certain content based on groups. Same kind of logic like categories and tags for posts.

**Comment by codezz** [comment]
Hi. to what groups are you referring to? the roles should take care of this exact thing. You can use User Role editor plugin and you will be able to assign multiple roles to users.
