### ISSUE TITLE
Critical Error After Updating Latest version 2.2.5

### ISSUE THREAD

**Issue by FarhanOnline** [StaxWP/visibility-logic-elementor#4]
Hi
after update latest version 2.2.5 my client website was complete down and showing Message **There has been a critical error on this website** so i was deactivate Visibility Logic for Elementor Plugin my site back to normal so pls quickly update plugin

**Comment by codezz** [comment]
Hi, can you get the message from the email so we can try and do some debugging? Also try the latest version since we added some fixes in the latest versions. Let me know

**Comment by geowrgetudor** [comment]
Fixed in 2.2.7
